from controller import get_controller_func
from ask_for_product import *
from ask_the_seller import *
from buy_product import *
from change_description import *
from change_name import *
from change_price import *
from check_for_sells import *
from delete_product import *
from login import *
from register import *
from upload_product import *